# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "weekone"
baseURL = "https://weekone.cc/"
theme = [
  "cmpt-flyfish",
  "FixIt", 
  "shortcode-docs-bookmark",
  "cmpt-translate"
]
defaultContentLanguage = "zh-cn"
disableLanguages = ["en", "zh-tw"]
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
buildDrafts = false
summaryLength = 0
titleCaseStyle = "ap"
capitalizeListTitles = false
timeZone = "Asia/Shanghai"
# the editor to use when creating new content
newContentEditor = "code"
# ignore some build errors
ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-get-gh-repo",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken",
  "warning-dev-version"
]

# Author configuration
[params.author]
name = "Your Name"
link = "https://yourwebsite.com"
email = "your@email.com"
avatar = "/images/avatar.jpg"

